services:
  - type: web
    name: neext-banner-api
    runtime: node
    rootDir: api
    buildCommand: npm install
    startCommand: node banner.js
    envVars:
      - key: NODE_ENV
        value: production
