services:
  - type: web
    name: neext-banner-api
    runtime: node
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libcairo2-dev \
        libpango1.0-dev \
        libjpeg-dev \
        libgif-dev \
        librsvg2-dev && \
      npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
