services:
  - type: web
    name: neext-banner-api
    runtime: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
